export component CliptooTray inherits SystemTrayIcon {
    icon: @image-url("../assets/cliptoo.svg");
    tooltip: @tr("Cliptoo — Clipboard Manager");
    title: "Cliptoo";

    callback toggle-window();
    callback quit-app();

    clicked => {
        toggle-window();
    }

    Menu {
        MenuItem {
            title: @tr("Show / Hide");
            activated => {
                toggle-window();
            }
        }

        MenuSeparator { }

        MenuItem {
            title: @tr("Quit");
            activated => {
                quit-app();
            }
        }
    }
}
