// cliptoo-core: backend library
// Modules are gated here; each owns its own error types via thiserror.

pub mod color;
pub mod compare;
pub mod content;
pub mod db;
pub mod export;
pub mod icon;
pub mod image;
pub mod logger;
pub mod maintenance;
pub mod send_to;
pub mod settings;
pub mod stats;
pub(crate) mod time;
pub mod transform;

// The canonical ClipData for UI rendering is generated by Slint from AppWindow.slint.
// The internal db::models::ClipData (with ClipType enum) is used for DB operations
// and mapped to the Slint type in the UI crate (see src/ui/src/main.rs).
pub use settings::Settings;
